### ISSUE TITLE
While using coupon retrival api it return error

### ISSUE THREAD

**Issue by amankumarjain** [voucherifyio/voucherify-python-sdk#15]
voucher = voucherify.get("TESTCOUPON25")

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/voucherify/client.py", line 106, in get
    path
  File "/usr/local/lib/python2.7/dist-packages/voucherify/client.py", line 38, in request
    raise VoucherifyError(e)
voucherify.client.VoucherifyError: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

```

**Comment by LukaszWiktor** [comment]
Hi @amankumarjain,

What's the exact version of python you're using? I see on the stack trace that it's 2.7, however, the patch component (2.7.x) may be crucial here. I verified that the voucherify-python-sdk works fine with python 2.7.11. 
The problem you reported is related to a SSL certificate. Voucherify API is using a SSL certificate with SNI (Server Name Indication). Python supports SNI starting from version 2.7.9.

**Comment by amankumarjain** [comment]
In the previous api call i was using get method, patch method i haven't used yet
My python version is 2.7.6. 
**It worked after installing requests[security] library i.e pip install requests[security]**

**Comment by LukaszWiktor** [comment]
Ok, thanks. 

As for patch I meant the 3rd component of the version number (`MAJOR.MINOR.PATCH`).

**Comment by amankumarjain** [comment]
oh, got it, i have 6 installed. thanks

**Comment by amankumarjain** [comment]
In python-sdk for voucherify where it is mentioned that it is using SNI, as in your sdk clinet code what i can see is you were using normal requests to make http calls.
`response = requests.request(
                method=method,
                url=url,
                headers=self.headers,
                timeout=self.timeout,
                **kwargs
            )`

**Comment by LukaszWiktor** [comment]
Actually it's the server that requires SNI. Naturally, the client has to handle it in the SSL handshake, however, it's the matter of the underlying libraries (`requests`, `OpenSSL`, etc.), not the voucherify-python-sdk itself.
